version: '3.9'

services:
  batch-notification:
    logging:
      options:
        max-size: 10m
    image: ${DOCKER_REGISTRY:-mc}/batch-notification:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "7021:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:8080
      SQL_CONNECTION: ${STAGING_SQL_CONNECTION}
      RABBIT_PASSWORD: ${STAGING_RABBIT_PASSWORD}
      REDIS_PASSWORD: ${STAGING_REDIS_PASSWORD}
      TZ: 'Asia/Tehran'
      PGTZ: 'Asia/Tehran'