version: '3.9'

services:
  batch-notification-test:
    container_name: batch-notification-test
    build:
      context: .
      dockerfile: Tests/AcceptanceTests/Dockerfile
    networks:
      - shared_network_test
networks:
  shared_network_test:
    external: true